version: '3.9'

services:
  mongo-mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=S3cret
  chess-de-back:
    # image: sterks/chess
    build: .
    ports:
      - 8001:8001
    volumes:
      - ~/apps/files:/app/bin/upload